version: '2'
services:
  softether:
    container_name: softether
    restart: unless-stopped
    image: meredithkm/softether
    volumes:
    - app:/usr/local/vpnserver/
    - logs:/var/log/vpnserver/
    network_mode: host
    cap_add:
      - NET_ADMIN

volumes:
  app:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/docker/softether/app
  logs:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/docker/softether/logs
